

spring:
  batch:
    jdbc:
      initialize-schema: always # 배치 메타데이터 테이블 자동 생성

  jpa:
    database: h2
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/snackpot;MODE=MySQL;
    username: sa
    password: 1234

  sql:
    init:
      mode: never